---
# Refer to https://metallb.universe.tf/configuration/ for
# available options.
configInline:
  address-pools:
    - name: default
      protocol: layer2
      addresses:
        - 192.168.122.10/32
