apiVersion: k0sctl.k0sproject.io/v1beta1
kind: Cluster
metadata:
  name: k0s-cluster
spec:
  hosts:
  #### Controllers
  #
  - role: controller
    ssh:
      address: 10.0.122.12
      user: core
      port: 22
  - role: controller
    ssh:
      address: 10.0.122.13
      user: core
      port: 22
  - role: controller
    ssh:
      address: 10.0.122.14
      user: core
      port: 22

  #### Workers
  #
  - role: worker
    ssh:
      address: 10.0.122.15
      user: core
      port: 22
  - role: worker
    ssh:
      address: 10.0.122.16
      user: core
      port: 22
  - role: worker
    ssh:
      address: 10.0.122.17
      user: core
      port: 22

  #### k0s configuration
  #
  k0s:
    version: v1.23.1+k0s.1
    config:
      apiVersion: k0s.k0sproject.io/v1beta1
      kind: Cluster
      metadata:
        name: k0s
      spec:
        api:
          externalAddress: 10.0.122.11
          sans:
            - 10.0.122.11
        storage:
          type: etcd
        network:
          provider: calico
          podCIDR: 10.244.0.0/16
          serviceCIDR: 10.96.0.0/12
        podSecurityPolicy:
          defaultPolicy: 00-k0s-privileged
        telemetry:
          enabled: false
        extensions:
          helm:
            repositories:
            - name: nfs-subdir-external-provisioner
              url: https://kubernetes-sigs.github.io/nfs-subdir-external-provisioner/
            - name: metallb
              url: https://metallb.github.io/metallb
            - name: haproxytech
              url: https://haproxytech.github.io/helm-charts
            charts:
            - name: nfs-subdir-external-provisioner
              chartname: nfs-subdir-external-provisioner/nfs-subdir-external-provisioner
              version: "4.0.14"
              namespace: storage
              values: |
                nfs:
                  server: "10.0.122.5"
                  path: "/filer/k8s"
                storageClass:
                  defaultClass: true
            - name: metallb
              chartname: metallb/metallb
              version: "v0.11.0"
              namespace: ingress
              values: |
                configInline:
                  address-pools:
                  - name: default
                    protocol: layer2
                    addresses:
                    - 10.0.122.10/32
            - name: haproxy-ingress
              chartname: haproxytech/kubernetes-ingress
              version: "1.18.1"
              namespace: ingress
              values: |
                controller:
                  kind: Deployment
                  ingressClassResource:
                    name: haproxy
                    default: true
                service:
                  type: LoadBalancer
