---
controller:
  kind: DaemonSet
  service:
    type: NodePort
    nodePorts:
      http: 30080
      https: 30443
      stat: 31024
    externalTrafficPolicy: "Local" # default is "Cluster", setting it to "Local" can helps in preserving client source IP
    ingressClassResource:
      name: haproxy
      default: true # since I only use a single ingress controller
